on:
    workflow_dispatch:
    push:
      branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Install dependencies
        run: |
            install.packages("readr")
            install.packages("gt")
            install.packages("rmarkdown")
            install.packages("tidyverse")
            install.packages("palmerpenguins")
            install.packages("docopt")
            install.packages("tidymodels")
            install.packages("tibble")
            install.packages("dplyr")
            install.packages("yardstick")
            install.packages("workflows")
            install.packages("rsample")
            install.packages("kknn")
            install.packages("devtools")
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
